### ISSUE TITLE
fadeIn() not fading in

### ISSUE THREAD

**Issue by ryancoke** [louisremi/jquery.transition.js#12]
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="jquery.transition.js" type="text/javascript"></script>
<script type="text/javascript">
    $("#test").click(function()
    {
        var self = $(this);
        self.fadeOut(1000, function() { self.fadeIn(1000); });
    });
</script>
```

When I don't include the jquery.transition.js I click the <div id="test"></div> and it will fade out then fade back in. But when I include the jquery.transition.js it will fade out but not fade in properly.

**Comment by louisremi** [comment]
You're right, it seems that using "hide","show" or "toggle" values causes such problems.
I can only think of a workaround:

```
self.animate({opacity: 0}, 1000).animate({opacity: 1}, 1000);
```

**Comment by louisremi** [comment]
Ok, I think I found where the problem lies. A fix is on the way.

**Comment by louisremi** [comment]
This problem has been fixed in the latest version of jquery.transition.js

Thanks for your patience,
Lr
