### ISSUE TITLE
animating 2 properties sets the last property in transition twice

### ISSUE THREAD

**Issue by fresh-bagel** [louisremi/jquery.transition.js#13]
when running an animation command with 2 properties the generated css on the element is wrong.
to reproduce run this command: 
$element.animate({left: '0px',opacity: 1},10000,'linear')
the css that is generated is:
-webkit-transition: opacity 10000ms linear, opacity 10000ms linear
instead of:
-webkit-transition:left 10000ms linear, opacity 10000ms linear

it seems that the last property is being inserted to the css instead of the first property.

**Comment by louisremi** [comment]
Wow, this seems to be a serious regression, how come I didn't spot it??
I'll investigate asap, thanks

**Comment by fresh-bagel** [comment]
great! thanks a lot!!

**Comment by louisremi** [comment]
Alright, I think I found the problem, fortunately it did not break the animations (or did it).
But that was a serious problem indeed, thanks for spotting it.
Patch is on the way

**Comment by louisremi** [comment]
Can you confirm that the last commit fixed the problem?

**Comment by fresh-bagel** [comment]
works great now.
once again - thanks a lot!

please notice that when I download the zip I don't get the latest revision with the fix - I had to take the file from the files list in order to test the fix (I don't have much experience with the git system so I don't know if this is the way it should be or not)

**Comment by louisremi** [comment]
Maybe you re-downloaded the zip before I uploaded the new one. The scripts in the current zip include the fix.
