### ISSUE TITLE
Does not handle colors correctly

### ISSUE THREAD

**Issue by bman654** [louisremi/jquery.transition.js#14]
Attempting to animate colors does not work if jquery.transition is included in the page.  See [this jsFiddle](http://jsfiddle.net/bman654/8bPA6/)

If you move the mouse over the black square, it should change colors.  But nothing happens.  If you remove the jquery.transition.js resource, then it works correctly.

I stepped into the code and the problem is that jquery.transition's new `animate` method is attempting to set _backgroundColor_ to _redpx_ (it thinks it needs to append a unit to the style property)

**Comment by louisremi** [comment]
good catch, here's a quick fix: 

```
$.cssNumber.backgroundColor = true;
$.cssNumber.color = true;
```

I'll fix the script asap.

**Comment by bman654** [comment]
don't forget the various other colors out there....

**Comment by louisremi** [comment]
Support for color and background-color has been added in the latest version of jquery.transition.js

Enjoy,
Lr
