### ISSUE TITLE
moar easing

### ISSUE THREAD

**Issue by matthewlein** [louisremi/jquery.transition.js#16]
Hey there,

Just taking a peek at this project and I saw that you turn it off for special easing. I approximated all the Penner equations that are doable in CSS, so you could include those as well. http://matthewlein.com/ceaser/

Ben Barnett did it in a similar project:
https://github.com/benbarnett/jQuery-Animate-Enhanced
and relavant pull:
https://github.com/benbarnett/jQuery-Animate-Enhanced/pull/23

**Comment by louisremi** [comment]
Hi @matthewlein,

This is some very interesting work you did there. I hope to find some time during this week to integrate these cubic-bezier easings in my plugin.

Regards,
Louis-Rémi

**Comment by louisremi** [comment]
This has been added in the latest version of jquery.transition.js

Enjoy,
Lr
