### ISSUE TITLE
Is slideDown() working?

### ISSUE THREAD

**Issue by munimkazia** [louisremi/jquery.transition.js#17]
$(x).slideDown() is just showing x without animation instead of sliding it down. slideUp() seems to be working.

**Comment by munimkazia** [comment]
Similarly, show('slow') seems to just show the item, but hide('slow') seems to work as expected.

**Comment by louisremi** [comment]
Hi,

Could you provide some test cases using jsfiddle? You can use this boilerplate and click to "fork" it: http://jsfiddle.net/qFM9G/1/

**Comment by munimkazia** [comment]
Here you go: http://jsfiddle.net/qFM9G/2/
Used a simple black div with slideDown and slideUp. 
As you can see, slideUp() seems to be animating properly, but slideDown() doesn't

**Comment by louisremi** [comment]
Thanks, I'll have a look at it.
Not during this week-end, though.

**Comment by louisremi** [comment]
Hi @munimkazia,

Have you tried without my plugin? I just did and the result is the same. 
This is the expected behavior of .slideUp() on "display: none;" elements.

Feel free to reopen the issue if you believe I'm wrong.

Best regards,
Lr

**Comment by munimkazia** [comment]
No @louisremi . I don't think you understood it. Have a look at this: http://jsfiddle.net/kYKd5/
For this, it shows the opening up animation properly. 

Also, I don't have permissions to open the issue.

**Comment by louisremi** [comment]
Note that jquery.transition.js is loaded twice in your first jsfiddle : once from beta.nh7.in/js/jquery.transition.min.js, and once from github, using jsfiddle's "manage resources" feature (menu on the left).
When I remove your version of jquery.transition.js, everything works fine. So I guess you are using an outdated version of the script.
Did you download the latest one?

**Comment by munimkazia** [comment]
Sorry for the confusion. I had no idea that jsfiddle has already loaded the library. 
However, this problem seems to persist when I host this simple test code (along with your direct github library link) here: 
http://munimkazia.com/test.html
Am I loading the library in the right place? 

Sorry for being pedantic about this. But I really believe something is amiss.

**Comment by louisremi** [comment]
Alright, I'll have a look into it asap.

**Comment by louisremi** [comment]
Alright, I confirm there was a problem with the previous version of jquery.transition.js
The update I was working one and that I released today happens to fix it, along with a couple of other bugs.
Get it from the download section.

Thanks for your patience,
Lr
