### ISSUE TITLE
Uncaught TypeError: Object #<cZ> has no method 'show'  in JQuery 1.8.x

### ISSUE THREAD

**Issue by codeuniquely** [louisremi/jquery.transition.js#22]
Call stack was 

Uncaught TypeError: Object #<cZ> has no method 'show' jquery.transition.js:321
doAnimation jquery.transition.js:321
p.extend.dequeue jquery.min.js:2
(anonymous function) jquery.min.js:2
p.extend.each jquery.min.js:2
p.fn.p.each jquery.min.js:2
p.fn.extend.queue jquery.min.js:2
jQuery.fn.extend.animate jquery.transition.js:374

**Comment by louisremi** [comment]
Yep, the script isn't compatible with 1.8
I'm closing this issue has it has already been reported. Thanks.

**Comment by codeuniquely** [comment]
OK,

But maybe you could add a note somewhere (in the readme) saying that it not to be used with 1.8 – until it has been fixed …

Steve
