### ISSUE TITLE
Style properties overriding CSS properties

### ISSUE THREAD

**Issue by brokenseal** [louisremi/jquery.transition.js#3]
Hi,
I'd like the plugin to add every single specified css property instead of going for the all-in-one css property to set a css transition.
For instance, if I want to set a transition-timing-function on the css and activate a transition with the plugin, the plugin actually overrides the transition-timing-function. The same goes with the transition-duration.

Cheers,
David

**Comment by louisremi** [comment]
Hi,
Such feature would be quite complex to implement and I currently don't have enough time.
Sorry.
