### ISSUE TITLE
$.animation() + scrollTop issue

### ISSUE THREAD

**Issue by jarred** [louisremi/jquery.transition.js#9]
When jquery.transition.js has been included in a page, the scrollTop animations (example below) stop working. Could jquery.transition be trying to animate this property with css transitions? (which, to my knowledge isn't possible)

```
  $('body').animate({
    scrollTop: 0
  }, 300);
```

Is there a way to whitelist properties? So that they're always animated with .js?

**Comment by louisremi** [comment]
Hi jarred, sorry for not looking at this issue earlier.
This bug should be easy to fix. Can you think of any other property that should also be white-listed?

Regards,
Lr

**Comment by louisremi** [comment]
Ok, this should be fixed now. Don't hesitate to warn me about other properties that could cause similar problems.

**Comment by jarred** [comment]
Thanks Louis! I can't think of any off the top of my head, but I will let you know.
